### PR TITLE
assertEquals between two arrays

### PR DESCRIPTION
**Pull request by hbekkouche**
since you implimented equals() methode in TaskView you can use assertEquals

### CODE REVIEW

**Comment by cherifGsoul** [comment]
@hbekkouche Great, the `equals` method is called on the `actual` and `expected` `ArrayList` instances, right?
Actually I'm checking the equality for the first item in both `ArrayList`, did you check it?

**Comment by cherifGsoul** [comment]
@hbekkouche thank you

**Comment by hbekkouche** [comment]
@cherifGsoul  ArrayList inherite the equals method from java.util.AbstractList
if you read the documentation:
"it iterates over both lists, comparing corresponding pairs of elements. If any comparison returns false, this method returns false."
https://docs.oracle.com/javase/8/docs/api/java/util/AbstractList.html#equals-java.lang.Object-

**Comment by cherifGsoul** [comment]
@hbekkouche I merged the PR yesterday, thank you!

**Pull request merged**
